class UserModel {
  // Optional identifier for the user, typically auto-generated by the database
  final int? id;
  // Name of the user
  final String name;
  // Age of the user
  final int age;
  // Phone number of the user
  final String phoneNumber;

  // Constructor to create a UserModel instance
  // with provided name, age, and phone number.

  UserModel({
    // id is optional because it is usually auto-generated by the database
    this.id,
    required this.name,
    required this.age,
    required this.phoneNumber,
  });

  // Method to convert the UserModel instance into a Map for database storage
  Map<String, dynamic> toMap() {
    return {
      // Include id (null if it's not assigned yet, such as during insertion)
      'id': id,
      // Store the name in the 'Name' column of the database
      'Name': name,
      // Store the age in the 'Age' column of the database
      'Age': age,
      // Store the phone number in the 'PhoneNumber' column
      'PhoneNumber': phoneNumber,
    };
  }

  // Factory constructor to create a UserModel instance from a Map (e.g., data from the database)
  factory UserModel.fromMap(Map<String, dynamic> map) {
    return UserModel(
      // Retrieve the id from the Map, typically set by the database
      id: map['id'],
      // Retrieve the name from the Map
      name: map['Name'],
      // Retrieve the age from the Map
      age: map['Age'],
      // Retrieve the phone number from the Map
      phoneNumber: map['PhoneNumber'],
    );
  }
}
